Iter13
Alekseyt9/ypmetrics pull request #13
Opened 2024-05-10 20:40 UTC by Alekseyt9

2024-05-11 09:51 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил пару комментариев по улучшению кода

2024-05-11 09:51 UTC, gonozov0 commented on internal/client/services/metrics.go
> +	stat.Lock.RUnlock()
лучше через defer сразу после вызова stat.Lock.RLock()

2024-05-11 09:51 UTC, gonozov0 commented on internal/common/retry.go
Это общая функциональность, которая пригодится тебе на любом другом проекте, поэтому лучше ее вынести в pkg

2024-05-11 09:51 UTC, gonozov0 commented on internal/server/handlers/gethandlers.go
> +	v, err := h.store.GetCounter(r.Context(), name)
респект, что уже понимаешь, почему стоит пробрасывать контекст от запроса

2024-05-11 09:51 UTC, gonozov0 commented on internal/server/handlers/gethandlers.go
> +	w.WriteHeader(http.StatusOK)
Я бы лучше вызывал метод Ping у Storage
и не понятно, почему тут решил не использовать контекст от запроса

2024-05-11 09:51 UTC, gonozov0 commented on internal/server/run/run.go
> +		}
Лучше поместить внутрь NewDBStorage

2024-05-11 09:51 UTC, gonozov0 commented on internal/server/storage/common.go
лучше назвать intefrace.go
по моему опыту, когда кто-то создает файл common.go или еще хуже целый пакет common, то это место превращается в свалку всего и вся, в которой сложно разбираться и рефакторить в дальнейшем

2024-05-11 09:51 UTC, gonozov0 commented on internal/server/storage/dbstorage.go
> +		);
По курсу вроде как не требуется, но я рекомендую сразу разобраться с механизмом миграций в go.

Для этого есть 2 популярные библиотеки:
- [golang-migrate/migrate](https://github.com/golang-migrate/migrate)
- [goose](https://github.com/pressly/goose)

Общий механизм одинаков:
1. создаешь отдельно папку в проекте с миграциями
2. описываешь на sql миграцию для создания таблиц, а также отдельную миграцию для ее откатывания (удаления созданных таблиц)
3. в логике инициализации Storage вызываешь применение всех твоих описанных миграций (это не особо правильный подход, в проде все миграции накатываются отдельно перед релизом, но т.к. мы подстраиваемся под прохождение автотестов, то в данном случае оправдано)

2024-05-13 11:46 UTC, Alekseyt9 commented
Добрый день! Спасибо за комментарии, вроде все поправил

2024-05-13 11:47 UTC, Alekseyt9 commented on internal/server/handlers/gethandlers.go
> +	w.WriteHeader(http.StatusOK)
Перенес в store.
По поводу контекста от запроса, тут просто забыл..

2024-05-13 11:48 UTC, Alekseyt9 commented
> Отличная работа 👍 Оставил пару комментариев по улучшению кода
Добрый день! Спасибо за комментарии, вроде все поправил

2024-05-13 14:33 UTC, gonozov0 approved these changes
Отлично, все поправил 💪

2024-05-16 18:30 UTC, merged