Iter5
Alekseyt9/ypmetrics pull request #5
Opened 2024-04-02 14:44 UTC by Alekseyt9

iter5

2024-04-03 08:24 UTC, gonozov0 requested changes
Прекрасная работа 💪
Довольно чистый и аккуратный код
Добавил пару комментов по возможным улучшениям

Если есть желание, рекомендую сразу подключить к проекту [golangci-lint](https://golangci-lint.run/) и [golden config](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322) для него
Для удобства лучше также [установить](https://github.com/gonozov0/go-echo-ddd-template/tree/main?tab=readme-ov-file#pre-commit-hooks) и [настроить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.pre-commit-config.yaml#L22) precommit хуки, чтобы линтер отрабатывал перед каждым коммитом
Дополнительно можно и в [ci добавить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.github/workflows/lint%26test.yml#L51)

2024-04-03 08:24 UTC, gonozov0 commented on cmd/agent/main.go
> +}
Все это лучше перенести в internal/run.go

2024-04-03 08:24 UTC, gonozov0 commented on cmd/server/main.go
> +}
аналогично

2024-04-03 08:24 UTC, gonozov0 commented on cmd/server/main_test.go
> +}
По факту ты тут не main тестируешь, а Router + handler-ы, также с ростом числа хендлеров этот файл станет огромным и нечитабельным
Т.к. это unit тесты, использующие memStorage, то правильнее будет их вынести в intrenal/server/handlers/handlers_test/ и разбить на также на файлы get и post handlers_test.go

2024-04-03 08:24 UTC, gonozov0 commented on internal/server/handlers/gethandlers.go
> +func HandleGetGauge(store storage.Storage) func(w http.ResponseWriter, r *http.Request) {
Давай лучше вместо оберток, возвращающих `func(w http.ResponseWriter, r *http.Request)` будем описывать сразу настоящие хендлеры

```go
type Handler struct {
     store storage.Storage
}

func NewHandler(store storage.Storage) *Handler {
	return &Handler{
		store: store
	}
}

func (h *Handler) GetGauge(w http.ResponseWriter, r *http.Request) {
```

2024-04-03 08:24 UTC, gonozov0 commented on internal/server/storage/storage.go
> +	result := make([]NameValueCounter, 0, len(store.gaugeData))
👍

2024-04-03 08:24 UTC, gonozov0 commented on cmd/server/main_test.go
> +	defer ts.Close()
Я бы также сделал для всех тестов на хендлеры отдельный Suite, чтобы не дубировать код 
[как пример](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/suite_test.go#L11)

2024-04-04 13:48 UTC, Alekseyt9 commented on cmd/agent/main.go
> +}
Добрый день! Спасибо за комментарии!
Перенес, кроме setEnv(), его переместил во flags.go, тк тоже используется один раз как и флаги

2024-04-04 13:48 UTC, Alekseyt9 commented on cmd/server/main_test.go
> +}
Все перенес, переписал на использование Suite

2024-04-04 13:49 UTC, Alekseyt9 commented on internal/server/handlers/gethandlers.go
> +func HandleGetGauge(store storage.Storage) func(w http.ResponseWriter, r *http.Request) {
Сделал, да, так короче получилось, спасибо

2024-04-04 13:49 UTC, Alekseyt9 commented on internal/server/storage/storage.go
> +	result := make([]NameValueCounter, 0, len(store.gaugeData))
Поправил :)

2024-04-04 13:51 UTC, Alekseyt9 commented on cmd/agent/main.go
> +}
Все по линтеру поправил, кроме 
internal\client\services\metrics.go:43:24: G404: Use of weak random number generator (math/rand instead of crypto/rand) (gosec)
        gMap["RandomValue"] = rand.Float64()
мне кажется, в данном случае это лишнее

2024-04-04 16:22 UTC, gonozov0 commented on cmd/agent/main.go
> +}
Согласен, чтобы не ругался на эту строку, можно в ней дописать комментарий `// nolint:gosec`

2024-04-04 16:24 UTC, gonozov0 approved these changes
Отличная работа 💪
Все моменты поправлены

2024-04-18 10:46 UTC, merged