Iter9
Alekseyt9/ypmetrics pull request #9
Opened 2024-04-25 11:09 UTC by Alekseyt9

2024-04-26 08:58 UTC, edylcrm requested changes

2024-04-26 08:58 UTC, edylcrm commented on internal/client/services/metrics.go
> +	CounterLock sync.RWMutex
Я бы здесь предложил оставить один mutex.

2024-04-26 08:58 UTC, edylcrm commented on internal/client/services/metrics.go
> +			panic(err)
Не советую использовать паники в бизнес логики. Когда происходит паника приложение аварийно завершается, это не штатная ситуация, например nil pointer exception. Здесь можно обойтись ошибкой и возвращать ее.

2024-04-26 08:58 UTC, edylcrm commented on internal/client/services/metrics.go
> +			panic(err)
Тоже самое что и комментарий выше

2024-04-26 08:58 UTC, edylcrm commented on internal/client/services/metrics.go
> +	for k, v := range stat.CounterMap {
Здесь точно нужно делать lock на все операции по отправке данных? Кажется, что правильней скопировать мапу под мьютектом и потом отправлять ее. Если по какой-то причине сервис куда отправляются метрики будет деградировать это может так же привести к деградации клиента

2024-04-26 08:58 UTC, edylcrm commented on internal/client/services/metrics.go
> +	stat.GaugeLock.RLock()
Здесь тоже самое про деградацию, что и комментарий выше

2024-04-26 10:43 UTC, Alekseyt9 commented
Спасибо за советы! Вроде все поправил

2024-04-27 10:31 UTC, edylcrm approved these changes

2024-05-06 12:45 UTC, merged